-- RenameIndex
ALTER INDEX "dashboard_branch_daily_counts_tenant_id_branch_id_metric_date_i" RENAME TO "dashboard_branch_daily_counts_tenant_id_branch_id_metric_da_idx";

-- RenameIndex
ALTER INDEX "dashboard_branch_daily_counts_tenant_id_scope_key_metric_date_k" RENAME TO "dashboard_branch_daily_counts_tenant_id_scope_key_metric_da_key";

-- RenameIndex
ALTER INDEX "dashboard_branch_stage_status_counts_tenant_id_scope_key_stage_" RENAME TO "dashboard_branch_stage_status_counts_tenant_id_scope_key_st_key";
