import {
  IndustryPreset,
  LeadStatus,
  MilestoneKey,
  TenantDisplayConfig,
} from '@leadops/shared';

const genericDisplayConfig: TenantDisplayConfig = {
  vocabulary: {
    leadSingular: 'Lead',
    leadPlural: 'Leads',
    leadCreateTitle: 'Create lead',
    dashboardTitle: 'Owner Dashboard',
    todayFollowupsTitle: 'Due Queue',
    bookingLabel: 'Won',
    reportLabel: 'Report',
    stageLabel: 'Stage',
    followupLabel: 'Follow-up',
    sidebarSubtitle: 'LeadOps',
    emptyLeads: 'No leads found. Adjust filters or create a new lead.',
    emptyFollowups: 'No overdue or due-today follow-ups.',
    statusLabels: {
      NEW: 'New',
      CONTACTED: 'Contacted',
      QUALIFIED: 'Qualified',
      PENDING: 'Pending',
      WON: 'Won',
      LOST: 'Lost',
    },
  },
  dashboardConfig: {
    cards: [
      { key: 'new', label: 'New', metricKey: 'new', icon: 'sparkles' },
      { key: 'pending', label: 'Pending', metricKey: 'pending', icon: 'circle-dashed' },
      { key: 'missed', label: 'Missed', metricKey: 'missed', icon: 'circle-off' },
      { key: 'won', label: 'Won', metricKey: 'won', icon: 'trophy' },
      { key: 'lost', label: 'Lost', metricKey: 'lost', icon: 'bar-chart' },
      {
        key: 'avgResponseMinutes',
        label: 'Avg First Response Time',
        metricKey: 'avgResponseMinutes',
        icon: 'clock',
      },
    ],
  },
  leadFieldsConfig: {
    fields: [
      { key: 'name', label: 'Lead name', type: 'text', required: true, section: 'core' },
      { key: 'nextFollowUpAt', label: 'Next follow-up', type: 'datetime', required: true, section: 'core' },
      { key: 'email', label: 'Email', type: 'email', required: false, section: 'core' },
      { key: 'phone', label: 'Phone', type: 'phone', required: false, section: 'core' },
      { key: 'note', label: 'Initial note', type: 'textarea', required: false, section: 'core' },
      {
        key: 'source',
        label: 'Source',
        type: 'select',
        required: false,
        section: 'intake',
        options: ['web', 'whatsapp', 'call', 'walkin', 'referral'],
      },
    ],
  },
  pipelineConfig: {
    stages: [
      {
        key: 'NEW',
        label: 'New',
        internalStatus: LeadStatus.NEW,
        allowedNext: ['CONTACTED', 'LOST'],
        followupPurposes: [
          { key: 'first_contact', label: 'First Contact' },
          { key: 'intake_completion', label: 'Complete Intake' },
        ],
        defaultFollowupPurposeKey: 'first_contact',
        followupGuidance: 'Confirm the first outreach objective and collect missing intake context.',
        terminal: false,
        order: 0,
      },
      {
        key: 'CONTACTED',
        label: 'Contacted',
        internalStatus: LeadStatus.CONTACTED,
        allowedNext: ['QUALIFIED', 'PENDING', 'LOST'],
        followupPurposes: [
          { key: 'qualification_call', label: 'Qualification Call' },
          { key: 'objection_handling', label: 'Handle Objections' },
        ],
        defaultFollowupPurposeKey: 'qualification_call',
        followupGuidance: 'Use this follow-up to qualify fit, intent, and next buying step.',
        terminal: false,
        order: 1,
      },
      {
        key: 'QUALIFIED',
        label: 'Qualified',
        internalStatus: LeadStatus.QUALIFIED,
        allowedNext: ['PENDING', 'WON', 'LOST'],
        followupPurposes: [
          { key: 'proposal_followup', label: 'Proposal Follow-up' },
          { key: 'decision_check', label: 'Decision Check' },
        ],
        defaultFollowupPurposeKey: 'proposal_followup',
        followupGuidance: 'Revisit the offer, confirm commercial fit, and move toward decision.',
        terminal: false,
        order: 2,
      },
      {
        key: 'PENDING',
        label: 'Pending',
        internalStatus: LeadStatus.PENDING,
        allowedNext: ['WON', 'LOST'],
        followupPurposes: [
          { key: 'decision_check', label: 'Decision Check' },
          { key: 'reactivation', label: 'Reactivation' },
        ],
        defaultFollowupPurposeKey: 'decision_check',
        followupGuidance: 'Clarify blockers, confirm timing, and decide whether to re-engage or close.',
        terminal: false,
        order: 3,
      },
      {
        key: 'WON',
        label: 'Won',
        internalStatus: LeadStatus.WON,
        allowedNext: [],
        followupPurposes: [
          { key: 'handoff_confirmation', label: 'Handoff Confirmation' },
        ],
        defaultFollowupPurposeKey: 'handoff_confirmation',
        followupGuidance: 'Use only when a final operational follow-up is needed after the win.',
        terminal: true,
        order: 4,
      },
      {
        key: 'LOST',
        label: 'Lost',
        internalStatus: LeadStatus.LOST,
        allowedNext: [],
        followupPurposes: [
          { key: 'loss_confirmation', label: 'Loss Confirmation' },
        ],
        defaultFollowupPurposeKey: 'loss_confirmation',
        followupGuidance: 'Terminal stage. Follow-ups here should be exceptional and usually short-lived.',
        terminal: true,
        order: 5,
      },
    ],
  },
  followupRules: {
    defaultLeadFollowupMinutes: 120,
    firstReminderMinutes: 30,
    escalationMinutes: 120,
    postReportFollowupDays: 3,
    postReportFollowupNote: 'Follow up after report delivery.',
  },
  themeConfig: {
    accentColor: '#2f90b7',
    sidebarTitle: 'LeadOps',
  },
  loginBranding: {
    eyebrow: 'HikmahOne',
    headline: 'Run your team with faster follow-ups and fewer missed opportunities.',
    subheadline:
      'Track enquiries, status movement, and follow-ups in one focused workspace built for high-velocity operations.',
    highlightOneLabel: 'Pipeline visibility',
    highlightOneText: 'See every enquiry in motion',
    highlightTwoLabel: 'Daily execution',
    highlightTwoText: 'Act on the right follow-up at the right time',
    calloutTitle: 'Built for operating teams',
    calloutText: 'Give owners and staff a clear view of what needs action across your lead pipeline.',
  },
  featureFlags: {
    aiAssist: true,
  },
  customEnquiryFields: [],
  testPackages: [],
};

const diagnosticsDisplayConfig: TenantDisplayConfig = {
  vocabulary: {
    leadSingular: 'Enquiry',
    leadPlural: 'Enquiries',
    leadCreateTitle: 'Create enquiry',
    dashboardTitle: 'Lab Operations Dashboard',
    todayFollowupsTitle: 'Due Queue',
    bookingLabel: 'Booking',
    reportLabel: 'Report',
    stageLabel: 'Lab workflow stage',
    followupLabel: 'Task',
    sidebarSubtitle: 'Lab LeadOps',
    emptyLeads: 'No enquiries found. Capture a new enquiry to start the workflow.',
    emptyFollowups: 'No overdue or due-today tasks.',
    statusLabels: {
      ENQUIRY_RECEIVED: 'Enquiry Received',
      BOOKING_CONFIRMED: 'Booking Confirmed',
      SAMPLE_COLLECTED: 'Sample Collected',
      REPORT_DELIVERED: 'Report Delivered',
      POST_REPORT_FOLLOWUP: 'Post-Report Follow-up',
      COMPLETED: 'Completed',
      NOT_INTERESTED: 'Not Interested',
    },
  },
  dashboardConfig: {
    cards: [
      { key: 'enquiriesToday', label: 'Enquiries Today', metricKey: 'enquiriesToday', icon: 'sparkles' },
      { key: 'bookingsToday', label: 'Bookings Today', metricKey: 'bookingsToday', icon: 'clipboard-check' },
      { key: 'pendingFollowups', label: 'Pending Follow-ups', metricKey: 'pendingFollowups', icon: 'circle-dashed' },
      { key: 'missedFollowups', label: 'Missed Follow-ups', metricKey: 'missedFollowups', icon: 'circle-off' },
      {
        key: 'avgResponseMinutes',
        label: 'Avg First Response Time',
        metricKey: 'avgResponseMinutes',
        icon: 'clock',
      },
      {
        key: 'postReportFollowupsDue',
        label: 'Post-Report Follow-ups Due',
        metricKey: 'postReportFollowupsDue',
        icon: 'activity',
      },
    ],
  },
  leadFieldsConfig: {
    fields: [
      { key: 'name', label: 'Patient name', type: 'text', required: true, section: 'core' },
      { key: 'nextFollowUpAt', label: 'Next follow-up', type: 'datetime', required: true, section: 'core' },
      { key: 'phone', label: 'Phone', type: 'phone', required: true, section: 'core' },
      { key: 'email', label: 'Email', type: 'email', required: false, section: 'core' },
      { key: 'note', label: 'Notes', type: 'textarea', required: false, section: 'core' },
      {
        key: 'testOrPackage',
        label: 'Test / Package',
        type: 'select',
        required: true,
        section: 'intake',
        options: ['CBC', 'LFT', 'KFT', 'Vitamin Profile', 'Diabetes Package'],
      },
      {
        key: 'homeCollection',
        label: 'Home Collection',
        type: 'boolean',
        required: true,
        section: 'intake',
      },
      {
        key: 'preferredSlot',
        label: 'Preferred Slot',
        type: 'datetime',
        required: false,
        section: 'intake',
      },
      { key: 'pincode', label: 'Pincode', type: 'text', required: true, section: 'intake' },
      {
        key: 'source',
        label: 'Source',
        type: 'select',
        required: true,
        section: 'intake',
        options: ['whatsapp', 'call', 'walkin', 'web'],
      },
    ],
  },
  pipelineConfig: {
    stages: [
      {
        key: 'ENQUIRY_RECEIVED',
        label: 'Enquiry Received',
        internalStatus: LeadStatus.NEW,
        allowedNext: ['BOOKING_CONFIRMED', 'NOT_INTERESTED'],
        followupPurposes: [
          { key: 'first_contact', label: 'First Contact' },
          { key: 'collect_test_details', label: 'Collect Test Details' },
        ],
        defaultFollowupPurposeKey: 'first_contact',
        followupGuidance: 'Confirm patient intent, required tests, and the fastest path to booking.',
        terminal: false,
        order: 0,
      },
      {
        key: 'BOOKING_CONFIRMED',
        label: 'Booking Confirmed',
        internalStatus: LeadStatus.PENDING,
        milestone: MilestoneKey.BOOKING_CONFIRMED,
        allowedNext: ['SAMPLE_COLLECTED', 'NOT_INTERESTED'],
        followupPurposes: [
          { key: 'confirm_booking', label: 'Confirm Booking' },
          { key: 'send_pretest_instructions', label: 'Send Pre-Test Instructions' },
        ],
        defaultFollowupPurposeKey: 'confirm_booking',
        followupGuidance: 'Confirm the slot, logistics, and patient preparation before collection.',
        terminal: false,
        order: 1,
      },
      {
        key: 'SAMPLE_COLLECTED',
        label: 'Sample Collected',
        internalStatus: LeadStatus.QUALIFIED,
        milestone: MilestoneKey.SAMPLE_COLLECTED,
        allowedNext: ['REPORT_DELIVERED', 'NOT_INTERESTED'],
        followupPurposes: [
          { key: 'collection_confirmation', label: 'Collection Confirmation' },
          { key: 'report_readiness_check', label: 'Report Readiness Check' },
        ],
        defaultFollowupPurposeKey: 'report_readiness_check',
        followupGuidance: 'Track report readiness and keep the patient informed about the next update.',
        terminal: false,
        order: 2,
      },
      {
        key: 'REPORT_DELIVERED',
        label: 'Report Delivered',
        internalStatus: LeadStatus.WON,
        milestone: MilestoneKey.REPORT_DELIVERED,
        allowedNext: ['POST_REPORT_FOLLOWUP', 'COMPLETED'],
        followupPurposes: [
          { key: 'share_report', label: 'Share Report' },
          { key: 'post_report_checkin', label: 'Post-Report Check-In' },
        ],
        defaultFollowupPurposeKey: 'share_report',
        followupGuidance: 'Confirm delivery and set up the next patient communication after report sharing.',
        terminal: false,
        order: 3,
      },
      {
        key: 'POST_REPORT_FOLLOWUP',
        label: 'Post-Report Follow-up',
        internalStatus: LeadStatus.PENDING,
        allowedNext: ['COMPLETED', 'NOT_INTERESTED'],
        followupPurposes: [
          { key: 'post_report_checkin', label: 'Post-Report Check-In' },
          { key: 'next_booking_push', label: 'Next Booking Push' },
        ],
        defaultFollowupPurposeKey: 'post_report_checkin',
        followupGuidance: 'Use this follow-up to close the loop, answer questions, and drive the next booking.',
        terminal: false,
        order: 4,
      },
      {
        key: 'COMPLETED',
        label: 'Completed',
        internalStatus: LeadStatus.WON,
        allowedNext: [],
        followupPurposes: [
          { key: 'completion_confirmation', label: 'Completion Confirmation' },
        ],
        defaultFollowupPurposeKey: 'completion_confirmation',
        followupGuidance: 'Terminal stage. Additional follow-up should be rare and intentional.',
        terminal: true,
        order: 5,
      },
      {
        key: 'NOT_INTERESTED',
        label: 'Not Interested',
        internalStatus: LeadStatus.LOST,
        allowedNext: [],
        followupPurposes: [
          { key: 'closure_check', label: 'Closure Check' },
        ],
        defaultFollowupPurposeKey: 'closure_check',
        followupGuidance: 'Terminal stage. Any remaining follow-up should be limited to explicit closure.',
        terminal: true,
        order: 6,
      },
    ],
  },
  followupRules: {
    defaultLeadFollowupMinutes: 120,
    firstReminderMinutes: 30,
    escalationMinutes: 180,
    postReportFollowupDays: 3,
    postReportFollowupNote: 'Follow up after report delivery to support next booking.',
  },
  themeConfig: {
    accentColor: '#0f7a78',
    sidebarTitle: 'Diagnostics LeadOps',
  },
  loginBranding: {
    eyebrow: 'HikmahOne',
    headline: 'Run your diagnostic lab with faster follow-ups and fewer missed patients.',
    subheadline:
      'Track patient enquiries, booking intent, report delivery, and post-report follow-ups in one focused workspace built for lab operations.',
    highlightOneLabel: 'Booking pipeline',
    highlightOneText: 'See every enquiry in motion',
    highlightTwoLabel: 'Report follow-through',
    highlightTwoText: 'Reduce missed post-report calls',
    calloutTitle: 'Built for diagnostics teams',
    calloutText:
      'Give reception, operations, and lab owners a clear view of what needs action across bookings and follow-ups.',
  },
  featureFlags: {
    aiAssist: true,
  },
  customEnquiryFields: [],
  testPackages: [
    { id: 'cbc', name: 'CBC', description: 'Complete blood count panel.', enabled: true },
    { id: 'lft', name: 'LFT', description: 'Liver function test panel.', enabled: true },
    { id: 'kft', name: 'KFT', description: 'Kidney function test panel.', enabled: true },
    { id: 'vitamin-profile', name: 'Vitamin Profile', description: 'Vitamin deficiency screening package.', enabled: true },
    { id: 'diabetes-package', name: 'Diabetes Package', description: 'Comprehensive diabetes monitoring package.', enabled: true },
  ],
};

function buildStageStatusLabels(stages: TenantDisplayConfig['pipelineConfig']['stages']): Record<string, string> {
  return Object.fromEntries(stages.map((stage) => [stage.key, stage.label]));
}

const cosmeticStages: TenantDisplayConfig['pipelineConfig']['stages'] = [
  {
    key: 'ENQUIRY_RECEIVED',
    label: 'Enquiry Received',
    internalStatus: LeadStatus.NEW,
    allowedNext: ['CONSULTATION_SCHEDULED', 'LOST'],
    followupPurposes: [
      { key: 'first_contact', label: 'First Contact' },
      { key: 'service_interest_review', label: 'Review Service Interest' },
    ],
    defaultFollowupPurposeKey: 'first_contact',
    followupGuidance: 'Confirm the treatment interest, patient goals, and the best consultation path.',
    terminal: false,
    order: 0,
  },
  {
    key: 'CONSULTATION_SCHEDULED',
    label: 'Consultation Scheduled',
    internalStatus: LeadStatus.CONTACTED,
    milestone: MilestoneKey.BOOKING_CONFIRMED,
    allowedNext: ['CONSULTATION_DONE', 'LOST'],
    followupPurposes: [
      { key: 'consultation_confirmation', label: 'Consultation Confirmation' },
      { key: 'previsit_preparation', label: 'Pre-Visit Preparation' },
    ],
    defaultFollowupPurposeKey: 'consultation_confirmation',
    followupGuidance: 'Confirm the doctor, slot, and any preparation needed before the consultation.',
    terminal: false,
    order: 1,
  },
  {
    key: 'CONSULTATION_DONE',
    label: 'Consultation Done',
    internalStatus: LeadStatus.QUALIFIED,
    allowedNext: ['PROCEDURE_PENDING', 'LOST'],
    followupPurposes: [
      { key: 'treatment_education', label: 'Treatment Education' },
      { key: 'price_followup', label: 'Price Follow-up' },
    ],
    defaultFollowupPurposeKey: 'treatment_education',
    followupGuidance: 'Use this follow-up to clarify recommendations, costs, and expected outcomes.',
    terminal: false,
    order: 2,
  },
  {
    key: 'PROCEDURE_PENDING',
    label: 'Procedure Pending',
    internalStatus: LeadStatus.PENDING,
    allowedNext: ['PROCEDURE_BOOKED', 'LOST'],
    followupPurposes: [
      { key: 'price_followup', label: 'Price Follow-up' },
      { key: 'decision_check', label: 'Decision Check' },
      { key: 'reactivation', label: 'Reactivation' },
    ],
    defaultFollowupPurposeKey: 'decision_check',
    followupGuidance: 'Clarify blockers, financing, and readiness before the patient books the procedure.',
    terminal: false,
    order: 3,
  },
  {
    key: 'PROCEDURE_BOOKED',
    label: 'Procedure Booked',
    internalStatus: LeadStatus.WON,
    allowedNext: [],
    followupPurposes: [
      { key: 'procedure_booking', label: 'Procedure Booking' },
      { key: 'handoff_confirmation', label: 'Handoff Confirmation' },
    ],
    defaultFollowupPurposeKey: 'procedure_booking',
    followupGuidance: 'Use only for final booking confirmation and internal handoff.',
    terminal: true,
    order: 4,
  },
  {
    key: 'LOST',
    label: 'Lost',
    internalStatus: LeadStatus.LOST,
    allowedNext: [],
    followupPurposes: [
      { key: 'loss_confirmation', label: 'Loss Confirmation' },
    ],
    defaultFollowupPurposeKey: 'loss_confirmation',
    followupGuidance: 'Terminal stage. Keep follow-up minimal unless the patient explicitly re-engages.',
    terminal: true,
    order: 5,
  },
];

const cosmeticDisplayConfig: TenantDisplayConfig = {
  vocabulary: {
    leadSingular: 'Enquiry',
    leadPlural: 'Enquiries',
    leadCreateTitle: 'Create enquiry',
    dashboardTitle: 'Cosmetic Clinic Dashboard',
    todayFollowupsTitle: 'Due Queue',
    bookingLabel: 'Consultation',
    reportLabel: 'Outcome',
    stageLabel: 'Consultation stage',
    followupLabel: 'Follow-up',
    sidebarSubtitle: 'Cosmetic LeadOps',
    emptyLeads: 'No enquiries found. Capture a new cosmetic enquiry to start the journey.',
    emptyFollowups: 'No overdue or due-today follow-ups.',
    statusLabels: buildStageStatusLabels(cosmeticStages),
  },
  dashboardConfig: {
    cards: [
      { key: 'enquiriesToday', label: 'Enquiries Today', metricKey: 'enquiriesToday', icon: 'sparkles' },
      { key: 'bookingsToday', label: 'Consultations Today', metricKey: 'bookingsToday', icon: 'clipboard-check' },
      { key: 'won', label: 'Procedures Booked', metricKey: 'won', icon: 'trophy' },
      { key: 'pendingFollowups', label: 'Pending Follow-ups', metricKey: 'pendingFollowups', icon: 'circle-dashed' },
      { key: 'missedFollowups', label: 'Missed Follow-ups', metricKey: 'missedFollowups', icon: 'circle-off' },
      { key: 'avgResponseMinutes', label: 'Avg First Response Time', metricKey: 'avgResponseMinutes', icon: 'clock' },
    ],
  },
  leadFieldsConfig: {
    fields: [
      { key: 'name', label: 'Patient name', type: 'text', required: true, section: 'core' },
      { key: 'nextFollowUpAt', label: 'Next follow-up', type: 'datetime', required: true, section: 'core' },
      { key: 'phone', label: 'Phone', type: 'phone', required: true, section: 'core' },
      { key: 'email', label: 'Email', type: 'email', required: false, section: 'core' },
      { key: 'note', label: 'Notes', type: 'textarea', required: false, section: 'core' },
      {
        key: 'serviceInterest',
        label: 'Service Interest',
        type: 'select',
        required: true,
        section: 'intake',
        options: ['Skin Treatment', 'Laser Hair Reduction', 'Anti-Aging', 'Hair Treatment', 'Body Contouring', 'Injectables', 'Other'],
      },
      {
        key: 'preferredDoctor',
        label: 'Preferred Specialist',
        type: 'select',
        required: false,
        section: 'intake',
        options: ['Dr. A', 'Dr. B', 'Any Available Specialist'],
      },
      {
        key: 'preferredSlot',
        label: 'Preferred Slot',
        type: 'datetime',
        required: false,
        section: 'intake',
      },
      {
        key: 'budgetRange',
        label: 'Budget Range',
        type: 'select',
        required: false,
        section: 'intake',
        options: ['Under 10k', '10k - 25k', '25k - 50k', '50k+'],
      },
      {
        key: 'source',
        label: 'Source',
        type: 'select',
        required: true,
        section: 'intake',
        options: ['Instagram', 'Meta Ads', 'Web', 'Call', 'Walk-in', 'Referral'],
      },
    ],
  },
  pipelineConfig: {
    stages: cosmeticStages,
  },
  followupRules: {
    defaultLeadFollowupMinutes: 120,
    firstReminderMinutes: 30,
    escalationMinutes: 120,
    postReportFollowupDays: 3,
    postReportFollowupNote: 'Follow up after treatment completion.',
  },
  themeConfig: {
    accentColor: '#c0657c',
    sidebarTitle: 'Cosmetic LeadOps',
  },
  loginBranding: {
    eyebrow: 'HikmahOne',
    headline: 'Run your cosmetic clinic with clearer consult follow-through and fewer dropped procedures.',
    subheadline:
      'Track patient enquiries, consultation scheduling, procedure intent, and follow-ups in one focused workspace for aesthetic teams.',
    highlightOneLabel: 'Consult pipeline',
    highlightOneText: 'Move enquiries toward booked consults',
    highlightTwoLabel: 'Procedure conversion',
    highlightTwoText: 'Keep high-intent cases from going cold',
    calloutTitle: 'Built for cosmetic clinics',
    calloutText: 'Give coordinators, doctors, and owners a shared view of consultation demand and procedure follow-through.',
  },
  featureFlags: {
    aiAssist: true,
  },
  customEnquiryFields: [],
  testPackages: [],
};

const dentalStages: TenantDisplayConfig['pipelineConfig']['stages'] = [
  {
    key: 'ENQUIRY_RECEIVED',
    label: 'Enquiry Received',
    internalStatus: LeadStatus.NEW,
    allowedNext: ['APPOINTMENT_BOOKED', 'LOST'],
    followupPurposes: [
      { key: 'first_contact', label: 'First Contact' },
      { key: 'symptom_review', label: 'Symptom Review' },
    ],
    defaultFollowupPurposeKey: 'first_contact',
    followupGuidance: 'Understand the treatment need, urgency, and the best path to a dental appointment.',
    terminal: false,
    order: 0,
  },
  {
    key: 'APPOINTMENT_BOOKED',
    label: 'Appointment Booked',
    internalStatus: LeadStatus.CONTACTED,
    milestone: MilestoneKey.BOOKING_CONFIRMED,
    allowedNext: ['CONSULTATION_DONE', 'LOST'],
    followupPurposes: [
      { key: 'appointment_confirmation', label: 'Appointment Confirmation' },
      { key: 'xray_or_records_followup', label: 'X-Ray / Records Follow-up' },
    ],
    defaultFollowupPurposeKey: 'appointment_confirmation',
    followupGuidance: 'Confirm the visit and collect any prior records or investigations needed before chair time.',
    terminal: false,
    order: 1,
  },
  {
    key: 'CONSULTATION_DONE',
    label: 'Consultation Done',
    internalStatus: LeadStatus.QUALIFIED,
    allowedNext: ['TREATMENT_PLAN_SHARED', 'LOST'],
    followupPurposes: [
      { key: 'treatment_plan_review', label: 'Treatment Plan Review' },
      { key: 'price_followup', label: 'Price Follow-up' },
    ],
    defaultFollowupPurposeKey: 'treatment_plan_review',
    followupGuidance: 'Use this follow-up to explain the plan, cost, number of sittings, and expected outcomes.',
    terminal: false,
    order: 2,
  },
  {
    key: 'TREATMENT_PLAN_SHARED',
    label: 'Treatment Plan Shared',
    internalStatus: LeadStatus.PENDING,
    allowedNext: ['PROCEDURE_BOOKED', 'LOST'],
    followupPurposes: [
      { key: 'treatment_plan_review', label: 'Treatment Plan Review' },
      { key: 'decision_check', label: 'Decision Check' },
      { key: 'reactivation', label: 'Reactivation' },
    ],
    defaultFollowupPurposeKey: 'decision_check',
    followupGuidance: 'Clarify objections, align the patient on plan acceptance, and move toward treatment booking.',
    terminal: false,
    order: 3,
  },
  {
    key: 'PROCEDURE_BOOKED',
    label: 'Procedure Booked',
    internalStatus: LeadStatus.WON,
    allowedNext: [],
    followupPurposes: [
      { key: 'procedure_booking', label: 'Procedure Booking' },
      { key: 'handoff_confirmation', label: 'Handoff Confirmation' },
    ],
    defaultFollowupPurposeKey: 'procedure_booking',
    followupGuidance: 'Use only for final booking confirmation and team handoff before the procedure.',
    terminal: true,
    order: 4,
  },
  {
    key: 'LOST',
    label: 'Lost',
    internalStatus: LeadStatus.LOST,
    allowedNext: [],
    followupPurposes: [
      { key: 'loss_confirmation', label: 'Loss Confirmation' },
    ],
    defaultFollowupPurposeKey: 'loss_confirmation',
    followupGuidance: 'Terminal stage. Follow-up here should only be used for explicit closure or later reactivation.',
    terminal: true,
    order: 5,
  },
];

const dentalDisplayConfig: TenantDisplayConfig = {
  vocabulary: {
    leadSingular: 'Enquiry',
    leadPlural: 'Enquiries',
    leadCreateTitle: 'Create enquiry',
    dashboardTitle: 'Dental Clinic Dashboard',
    todayFollowupsTitle: 'Due Queue',
    bookingLabel: 'Appointment',
    reportLabel: 'Treatment',
    stageLabel: 'Dental workflow stage',
    followupLabel: 'Follow-up',
    sidebarSubtitle: 'Dental LeadOps',
    emptyLeads: 'No enquiries found. Capture a new dental enquiry to start the case.',
    emptyFollowups: 'No overdue or due-today follow-ups.',
    statusLabels: buildStageStatusLabels(dentalStages),
  },
  dashboardConfig: {
    cards: [
      { key: 'enquiriesToday', label: 'Enquiries Today', metricKey: 'enquiriesToday', icon: 'sparkles' },
      { key: 'bookingsToday', label: 'Appointments Today', metricKey: 'bookingsToday', icon: 'clipboard-check' },
      { key: 'won', label: 'Procedures Booked', metricKey: 'won', icon: 'trophy' },
      { key: 'pendingFollowups', label: 'Pending Follow-ups', metricKey: 'pendingFollowups', icon: 'circle-dashed' },
      { key: 'missedFollowups', label: 'Missed Follow-ups', metricKey: 'missedFollowups', icon: 'circle-off' },
      { key: 'avgResponseMinutes', label: 'Avg First Response Time', metricKey: 'avgResponseMinutes', icon: 'clock' },
    ],
  },
  leadFieldsConfig: {
    fields: [
      { key: 'name', label: 'Patient name', type: 'text', required: true, section: 'core' },
      { key: 'nextFollowUpAt', label: 'Next follow-up', type: 'datetime', required: true, section: 'core' },
      { key: 'phone', label: 'Phone', type: 'phone', required: true, section: 'core' },
      { key: 'email', label: 'Email', type: 'email', required: false, section: 'core' },
      { key: 'note', label: 'Notes', type: 'textarea', required: false, section: 'core' },
      {
        key: 'treatmentInterest',
        label: 'Treatment Interest',
        type: 'select',
        required: true,
        section: 'intake',
        options: ['Braces', 'Aligners', 'Root Canal', 'Implant', 'Cleaning', 'Whitening', 'Extraction', 'General Checkup', 'Other'],
      },
      {
        key: 'preferredDentist',
        label: 'Preferred Dentist',
        type: 'select',
        required: false,
        section: 'intake',
        options: ['Dr. A', 'Dr. B', 'Any Available Dentist'],
      },
      {
        key: 'painLevel',
        label: 'Pain Level',
        type: 'select',
        required: true,
        section: 'intake',
        options: ['Low', 'Moderate', 'High', 'Emergency'],
      },
      {
        key: 'preferredSlot',
        label: 'Preferred Slot',
        type: 'datetime',
        required: false,
        section: 'intake',
      },
      {
        key: 'source',
        label: 'Source',
        type: 'select',
        required: true,
        section: 'intake',
        options: ['Google', 'Meta Ads', 'Call', 'Walk-in', 'Referral', 'Web'],
      },
    ],
  },
  pipelineConfig: {
    stages: dentalStages,
  },
  followupRules: {
    defaultLeadFollowupMinutes: 120,
    firstReminderMinutes: 30,
    escalationMinutes: 120,
    postReportFollowupDays: 3,
    postReportFollowupNote: 'Follow up after treatment completion.',
  },
  themeConfig: {
    accentColor: '#2563eb',
    sidebarTitle: 'Dental LeadOps',
  },
  loginBranding: {
    eyebrow: 'HikmahOne',
    headline: 'Run your dental clinic with tighter appointment follow-through and fewer dropped treatment plans.',
    subheadline:
      'Track patient enquiries, appointment booking, treatment plan follow-ups, and procedure conversion in one focused workspace for dental teams.',
    highlightOneLabel: 'Appointment flow',
    highlightOneText: 'Convert enquiries into chair time faster',
    highlightTwoLabel: 'Treatment acceptance',
    highlightTwoText: 'Keep plans moving toward booked procedures',
    calloutTitle: 'Built for dental clinics',
    calloutText: 'Give front desk teams and dentists a clear view of appointment demand, plan acceptance, and next actions.',
  },
  featureFlags: {
    aiAssist: true,
  },
  customEnquiryFields: [],
  testPackages: [],
};

const doctorOpdStages: TenantDisplayConfig['pipelineConfig']['stages'] = [
  {
    key: 'ENQUIRY_RECEIVED',
    label: 'Enquiry Received',
    internalStatus: LeadStatus.NEW,
    allowedNext: ['APPOINTMENT_BOOKED', 'LOST'],
    followupPurposes: [
      { key: 'first_contact', label: 'First Contact' },
      { key: 'doctor_assignment', label: 'Doctor Assignment' },
    ],
    defaultFollowupPurposeKey: 'first_contact',
    followupGuidance: 'Capture speciality need, visit type, and move the patient toward the right OPD slot.',
    terminal: false,
    order: 0,
  },
  {
    key: 'APPOINTMENT_BOOKED',
    label: 'Appointment Booked',
    internalStatus: LeadStatus.CONTACTED,
    milestone: MilestoneKey.BOOKING_CONFIRMED,
    allowedNext: ['VISIT_COMPLETED', 'LOST'],
    followupPurposes: [
      { key: 'appointment_confirmation', label: 'Appointment Confirmation' },
      { key: 'doctor_assignment', label: 'Doctor Assignment' },
    ],
    defaultFollowupPurposeKey: 'appointment_confirmation',
    followupGuidance: 'Confirm the OPD slot, doctor availability, and any records the patient should bring.',
    terminal: false,
    order: 1,
  },
  {
    key: 'VISIT_COMPLETED',
    label: 'Visit Completed',
    internalStatus: LeadStatus.QUALIFIED,
    allowedNext: ['FOLLOWUP_RECOMMENDED', 'LOST'],
    followupPurposes: [
      { key: 'visit_reminder', label: 'Visit Reminder' },
      { key: 'care_plan_review', label: 'Care Plan Review' },
    ],
    defaultFollowupPurposeKey: 'care_plan_review',
    followupGuidance: 'Close the loop after the consultation and align on the next follow-up recommendation.',
    terminal: false,
    order: 2,
  },
  {
    key: 'FOLLOWUP_RECOMMENDED',
    label: 'Follow-up Recommended',
    internalStatus: LeadStatus.PENDING,
    allowedNext: ['FOLLOWUP_BOOKED', 'LOST'],
    followupPurposes: [
      { key: 'followup_booking', label: 'Follow-up Booking' },
      { key: 'reactivation', label: 'Reactivation' },
    ],
    defaultFollowupPurposeKey: 'followup_booking',
    followupGuidance: 'Use this stage to get the patient back into the schedule for the recommended review.',
    terminal: false,
    order: 3,
  },
  {
    key: 'FOLLOWUP_BOOKED',
    label: 'Follow-up Booked',
    internalStatus: LeadStatus.WON,
    allowedNext: [],
    followupPurposes: [
      { key: 'followup_booking', label: 'Follow-up Booking' },
      { key: 'handoff_confirmation', label: 'Handoff Confirmation' },
    ],
    defaultFollowupPurposeKey: 'followup_booking',
    followupGuidance: 'Use only for final confirmation after the patient books the next OPD visit.',
    terminal: true,
    order: 4,
  },
  {
    key: 'LOST',
    label: 'Lost',
    internalStatus: LeadStatus.LOST,
    allowedNext: [],
    followupPurposes: [
      { key: 'loss_confirmation', label: 'Loss Confirmation' },
    ],
    defaultFollowupPurposeKey: 'loss_confirmation',
    followupGuidance: 'Terminal stage. Any further contact should be deliberate and limited.',
    terminal: true,
    order: 5,
  },
];

const doctorOpdDisplayConfig: TenantDisplayConfig = {
  vocabulary: {
    leadSingular: 'Patient Enquiry',
    leadPlural: 'Patient Enquiries',
    leadCreateTitle: 'Create patient enquiry',
    dashboardTitle: 'Doctor OPD Dashboard',
    todayFollowupsTitle: 'Due Queue',
    bookingLabel: 'Appointment',
    reportLabel: 'Visit',
    stageLabel: 'OPD workflow stage',
    followupLabel: 'Follow-up',
    sidebarSubtitle: 'OPD LeadOps',
    emptyLeads: 'No patient enquiries found. Capture a new enquiry to schedule the next OPD visit.',
    emptyFollowups: 'No overdue or due-today follow-ups.',
    statusLabels: buildStageStatusLabels(doctorOpdStages),
  },
  dashboardConfig: {
    cards: [
      { key: 'enquiriesToday', label: 'Patient Enquiries Today', metricKey: 'enquiriesToday', icon: 'sparkles' },
      { key: 'bookingsToday', label: 'Appointments Today', metricKey: 'bookingsToday', icon: 'clipboard-check' },
      { key: 'won', label: 'Follow-ups Booked', metricKey: 'won', icon: 'trophy' },
      { key: 'pendingFollowups', label: 'Pending Follow-ups', metricKey: 'pendingFollowups', icon: 'circle-dashed' },
      { key: 'missedFollowups', label: 'Missed Follow-ups', metricKey: 'missedFollowups', icon: 'circle-off' },
      { key: 'avgResponseMinutes', label: 'Avg First Response Time', metricKey: 'avgResponseMinutes', icon: 'clock' },
    ],
  },
  leadFieldsConfig: {
    fields: [
      { key: 'name', label: 'Patient name', type: 'text', required: true, section: 'core' },
      { key: 'nextFollowUpAt', label: 'Next follow-up', type: 'datetime', required: true, section: 'core' },
      { key: 'phone', label: 'Phone', type: 'phone', required: true, section: 'core' },
      { key: 'email', label: 'Email', type: 'email', required: false, section: 'core' },
      { key: 'note', label: 'Notes', type: 'textarea', required: false, section: 'core' },
      {
        key: 'departmentOrSpeciality',
        label: 'Department / Speciality',
        type: 'select',
        required: true,
        section: 'intake',
        options: [],
      },
      {
        key: 'preferredDoctor',
        label: 'Preferred Doctor',
        type: 'select',
        required: false,
        section: 'intake',
        options: [],
      },
      {
        key: 'visitType',
        label: 'Visit Type',
        type: 'select',
        required: true,
        section: 'intake',
        options: ['New Consult', 'Follow-up', 'Second Opinion'],
      },
      {
        key: 'preferredSlot',
        label: 'Preferred Slot',
        type: 'datetime',
        required: false,
        section: 'intake',
      },
      {
        key: 'source',
        label: 'Source',
        type: 'select',
        required: true,
        section: 'intake',
        options: ['Call', 'Walk-in', 'Web', 'Referral', 'WhatsApp'],
      },
    ],
  },
  pipelineConfig: {
    stages: doctorOpdStages,
  },
  followupRules: {
    defaultLeadFollowupMinutes: 120,
    firstReminderMinutes: 30,
    escalationMinutes: 120,
    postReportFollowupDays: 3,
    postReportFollowupNote: 'Follow up after the completed OPD visit.',
  },
  themeConfig: {
    accentColor: '#0f766e',
    sidebarTitle: 'OPD LeadOps',
  },
  loginBranding: {
    eyebrow: 'HikmahOne',
    headline: 'Run your OPD clinic with faster appointment conversion and stronger follow-up booking.',
    subheadline:
      'Track patient enquiries, doctor assignment, OPD visits, and recommended follow-up bookings in one focused workspace.',
    highlightOneLabel: 'Appointment intake',
    highlightOneText: 'Route patients to the right doctor faster',
    highlightTwoLabel: 'Follow-up capture',
    highlightTwoText: 'Turn completed visits into booked reviews',
    calloutTitle: 'Built for OPD clinics',
    calloutText: 'Give front desk teams and doctors a clear view of appointment demand, visit completion, and next follow-up bookings.',
  },
  featureFlags: {
    aiAssist: true,
  },
  customEnquiryFields: [],
  testPackages: [],
  opdDirectory: {
    departments: [],
    doctors: [],
  },
};

export function getPresetDisplayConfig(preset: IndustryPreset): TenantDisplayConfig {
  switch (preset) {
    case IndustryPreset.DIAGNOSTICS_LAB:
      return diagnosticsDisplayConfig;
    case 'COSMETIC_CLINIC':
      return cosmeticDisplayConfig;
    case 'DENTAL_CLINIC':
      return dentalDisplayConfig;
    case 'DOCTOR_OPD_CLINIC':
      return doctorOpdDisplayConfig;
    case IndustryPreset.GENERIC:
    default:
      return genericDisplayConfig;
  }
}
